version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - etl_network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: etl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - etl_network

  dagster:
    build: ./dagster
    container_name: etl_dagster
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - etl_network


volumes:
  postgres_data:

networks:
  etl_network:
    driver: bridge
